### ISSUE TITLE
Config variables

### ISSUE THREAD

**Issue by nachonavarro** [juneau-project/juneau#6]
Unfortunately with the new change `config-default.py` does not work due to Python's file name requirements (i.e. you can't do something like `from juneau import config-default`).

I think all of this is part of a bigger issue. At the moment there's a very tight coupling between Juneau and the config variable the users wants to use. The user has to manually change the source files and put their username, password, etc. A more natural solution would be either to have environment variables, e.g. `SQL_USERNAME` that the user can modify, or use a more robust approach like [Hydra](https://hydra.cc/), in particular [this](https://hydra.cc/docs/tutorial/config_file), which has been developed at Facebook Research and allows us to config complex applications through YAML files.

What do you think?

**Comment by nachonavarro** [comment]
With environment variables, it could be as simple as

```python
import os

sql_name = os.environ.get('SQL_NAME', 'postgres')  # default to postgres
sql_password = os.environ.get('SQL_PASSWORD', 'habitat1')
# etc
```

**Comment by omry** [comment]
With Hydra (or just OmegaConf really) it can be as simple as : 

**config.yaml**:
```yaml
sql:
  name: ${env:SQL_NAME,postgres}
  password: ${env:SQL_PASSWORD,habitat1}
```

try:
```python
cfg = OmegaConf.create("config.yaml") # with the content above
print(cfg.sql.name, cfg.sql.password)
```
